require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.keymaps"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.telescope"
require "user.alpha"
require "user.autopairs"
require "user.cmp"
require "user.lsp"
require "user.toggleterm"

